### ISSUE TITLE
Unsupported URL protocol when reading and parsing guide for Radarr

### ISSUE THREAD

**Issue by aldoborrero** [rcdailey/trash-updater#18]
When using `trash` to synchronize settings on Radarr:

```sh
trash radarr -c config/trash-updater/trash.yml
```

It appears the following error:

```
[INF] Processing Quality Definition: Movie
[INF] Number of updated qualities: 0
[INF] Requesting and parsing guide markdown
[ERR] Unrecoverable Exception
LibGit2Sharp.LibGit2SharpException: unsupported URL protocol
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts)
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options)
   at TrashLib.Radarr.CustomFormat.Guide.LocalRepoCustomFormatJsonParser.<GetCustomFormatJsonAsync>b__3_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at TrashLib.Radarr.CustomFormat.Guide.LocalRepoCustomFormatJsonParser.GetCustomFormatJsonAsync()
   at TrashLib.Radarr.CustomFormat.Processors.GuideProcessor.BuildGuideDataAsync(IReadOnlyList`1 config, CustomFormatCache cache)
   at TrashLib.Radarr.CustomFormat.CustomFormatUpdater.Process(Boolean isPreview, RadarrConfiguration config)
   at Trash.Command.RadarrCommand.Process()
   at Trash.Command.Helpers.ServiceCommand.ExecuteAsync(IConsole console)
Exiting due to previous exception
```

**Comment by rcdailey** [comment]
Thanks for the bug report. I'm not able to reproduce this error. 

- Are you able to consistently reproduce this?
- Please run again with the `-d` option for additional debug logs.
- Send me the file `%APPDATA%\trash-updater\repo\.git\config` (windows path). On linux it's based in `~/.config/trash-updater`.

**Comment by aldoborrero** [comment]
Hi, thanks for letting me know! You gave me the answer to the issue (which is not an issue per se). I forgot that I had in my [`home-manager`](https://github.com/nix-community/home-manager) config the following entry for git:

```
url."ssh://git@github.com/".insteadOf = "https://github.com/"
```

That was causing the URL to be replaced incorrectly for `trash`. After removing the line, the program worked fine. So, closing this issue.
