### ISSUE TITLE
Can't run movie quality definitions script - Debian 11

### ISSUE THREAD

**Issue by gyCfjSnO** [rcdailey/trash-updater#20]
I am trying to run the script for the movie quality definitions but I am getting the below error message, .NET is installed and I am running Debian 11. When I throw the URL into web browser it can be accessed no problems.

```[INF] Processing Quality Definition: Movie
[ERR] HTTP error while communicating with Radarr
Flurl.Http.FlurlHttpException: Call failed. The SSL connection could not be established, see inner exception: GET https://127.0.0.1/radarr/api/v3/qualitydefinition?apikey=REDACTED
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   --- End of inner exception stack trace ---
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at TrashLib.Radarr.QualityDefinition.Api.QualityDefinitionService.GetQualityDefinition()
   at TrashLib.Radarr.QualityDefinition.RadarrQualityDefinitionUpdater.ProcessQualityDefinition(IEnumerable`1 guideQuality)
   at TrashLib.Radarr.QualityDefinition.RadarrQualityDefinitionUpdater.Process(Boolean isPreview, RadarrConfiguration config)
   at Trash.Command.RadarrCommand.Process()
Exiting due to previous exception```

**Comment by rcdailey** [comment]
Looks like the issue is that you're using a self-signed certificate. That is not a scenario I have tested. I would recommend you use `http` if you're going to use `localhost`. `https` *will* work but it requires an actual certificate, like one from letsencrypt.

**Comment by PlzDontScrobbleMe** [comment]
any chance to add `insecure` option to config (and skip the ssl verification on the api calls)?
ive got the same problem, all my setup is via https only with private ca signed certs...

**Comment by gyCfjSnO** [comment]
> Looks like the issue is that you're using a self-signed certificate. That is not a scenario I have tested. I would recommend you use `http` if you're going to use `localhost`. `https` _will_ work but it requires an actual certificate, like one from letsencrypt.

I have tried using http in the .yaml but still get same error message

**Comment by rcdailey** [comment]
> I have tried using http in the .yaml but still get same error message

Most likely, Radarr is redirecting `http` to `https`. If you are getting the same error message, it's due to SSL.

I'm working on adding settings support. I'll make sure that I add an option to disable SSL as well.

**Comment by Fienjouricen** [comment]
It worked for me after adding my self signed certificate into trust store of my linux. I'm using ubuntu 20.04 and done following steps:
1. Copy the `.crt` file to `/usr/local/share/ca-certificates/`
2. Run `sudo update-ca-certificates`

**Comment by rcdailey** [comment]
Check out release v1.7.0 which has a new settings file and option inside of it to disable SSL verification. There's a Settings Reference page in the wiki with more details.

**Comment by gyCfjSnO** [comment]
> Check out release v1.7.0 which has a new settings file and option inside of it to disable SSL verification. There's a Settings Reference page in the wiki with more details.

Still getting same error message.

```htpc@HTPC:~$ ./trash sonarr && ./trash radarr
[INF] Processing Release Profile: Series
[ERR] HTTP error while communicating with Sonarr
Flurl.Http.FlurlHttpException: Call failed. The SSL connection could not be established, see inner exception: GET https://127.0.0.1/8989/api/v3/system/status?apikey=REDACTED
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch```

**Comment by rcdailey** [comment]
The ssl verification setting goes into the settings file not the trash.yml

**Comment by gyCfjSnO** [comment]
> ./trash sonarr && ./trash radarr

I now get this error when trying to run it...

```
htpc@HTPC:~$ ./trash sonarr && ./trash radarr
[WRN] Security Risk: Certificate validation is being DISABLED because setting `enable_ssl_certificate_validation` is set to `false`
[INF] Processing Release Profile: Series
[ERR] HTTP error while communicating with Sonarr
Flurl.Http.FlurlHttpException: Call failed with status code 401 (Unauthorized): GET https://127.0.0.1/sonarr/api/v3/system/status?apikey=REDACTED
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson(Task`1 response)
   at TrashLib.Sonarr.SonarrCompatibility.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext() in D:\a\trash-updater\trash-updater\src\TrashLib\Sonarr\SonarrCompatibility.cs:line 14
--- End of stack trace from previous location ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:line 19
   at System.Reactive.ExceptionHelpers.Throw(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs:line 16
   at System.Reactive.Subjects.AsyncSubject`1.GetResult() in /_/Rx.NET/Source/src/System.Reactive/Subjects/AsyncSubject.cs:line 430
   at TrashLib.Sonarr.ReleaseProfile.ReleaseProfileUpdater.DoVersionEnforcement() in D:\a\trash-updater\trash-updater\src\TrashLib\Sonarr\ReleaseProfile\ReleaseProfileUpdater.cs:line 65
   at TrashLib.Sonarr.ReleaseProfile.ReleaseProfileUpdater.ProcessReleaseProfiles(IDictionary`2 profiles, ReleaseProfileConfig config) in D:\a\trash-updater\trash-updater\src\TrashLib\Sonarr\ReleaseProfile\ReleaseProfileUpdater.cs:line 139
   at TrashLib.Sonarr.ReleaseProfile.ReleaseProfileUpdater.Process(Boolean isPreview, SonarrConfiguration config) in D:\a\trash-updater\trash-updater\src\TrashLib\Sonarr\ReleaseProfile\ReleaseProfileUpdater.cs:line 53
   at Trash.Command.SonarrCommand.Process() in D:\a\trash-updater\trash-updater\src\Trash\Command\SonarrCommand.cs:line 54
Exiting due to previous exception
```

**Comment by rcdailey** [comment]
Your hint is here:

> 401 (Unauthorized)

This means you are not authorized to connect to Sonarr. Check your API key.

**Comment by rcdailey** [comment]
I'm going to lock this issue. @gyCfjSnO please start a new discussion for further support if you still encounter issues.
