### ISSUE TITLE
Radarr V4 Support

### ISSUE THREAD

**Issue by darsh12** [rcdailey/trash-updater#42]
Hi,
I am trying to get the trash-updater working, however I am using radarr v4 and it seems it is currently not supported

```
2022-03-03 12:32:50.193 -08:00 [DBG] Custom format cache does not exist; proceeding without it
2022-03-03 12:32:52.440 -08:00 [DBG] HTTP Request to http://hostname:9999/api/v3/customformat?apikey=SNIP
2022-03-03 12:32:52.569 -08:00 [DBG] HTTP Request to http://hostname:9999/radarr/api/v3/customformat?apikey=SNIP
2022-03-03 12:32:52.695 -08:00 [DBG] HTTP Response 200 from http://hostname:9999/radarr/api/v3/customformat?apikey=SNIP
2022-03-03 12:32:52.696 -08:00 [DBG] HTTP Response 302 from http://hostname:9999/api/v3/customformat?apikey=SNIP
2022-03-03 12:32:52.936 -08:00 [DBG] HTTP Request to http://hostname:9999/api/v3/customformat?apikey=SNIP
2022-03-03 12:32:52.939 -08:00 [DBG] HTTP Request to http://hostname:9999/radarr/api/v3/customformat?apikey=SNIP
2022-03-03 12:32:52.945 -08:00 [DBG] HTTP Response 200 from http://hostname:9999/radarr/api/v3/customformat?apikey=SNIP
2022-03-03 12:32:52.946 -08:00 [DBG] HTTP Response 302 from http://hostname:9999/api/v3/customformat?apikey=SNIP
2022-03-03 12:32:52.965 -08:00 [ERR] HTTP error while communicating with Radarr
Flurl.Http.FlurlParsingException: Response could not be deserialized to JSON: GET http://localhost:9999/radarr/api/v3/customformat?apikey=f7b15e28f1014ebe9671d4103d626dae
 ---> Newtonsoft.Json.JsonSerializationException: Deserialized JSON type 'Newtonsoft.Json.Linq.JArray' is not compatible with expected type 'Newtonsoft.Json.Linq.JObject'. Path '', line 1, position 2.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(JsonReader reader, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Flurl.Http.Configuration.NewtonsoftJsonSerializer.Deserialize[T](Stream stream)
   at Flurl.Http.FlurlResponse.GetJsonAsync[T]()
   --- End of inner exception stack trace ---
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlResponse.GetJsonAsync[T]()
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at TrashLib.Radarr.CustomFormat.Api.CustomFormatService.CreateCustomFormat(ProcessedCustomFormatData cf) in D:\a\trash-updater\trash-updater\src\TrashLib\Radarr\CustomFormat\Api\CustomFormatService.cs:line 28
   at TrashLib.Radarr.CustomFormat.Processors.PersistenceSteps.CustomFormatApiPersistenceStep.Process(ICustomFormatService api, CustomFormatTransactionData transactions) in D:\a\trash-updater\trash-updater\src\TrashLib\Radarr\CustomFormat\Processors\PersistenceSteps\CustomFormatApiPersistenceStep.cs:line 12
   at TrashLib.Radarr.CustomFormat.Processors.PersistenceProcessor.PersistCustomFormats(IReadOnlyCollection`1 guideCfs, IEnumerable`1 deletedCfsInCache, IDictionary`2 profileScores) in D:\a\trash-updater\trash-updater\src\TrashLib\Radarr\CustomFormat\Processors\PersistenceProcessor.cs:line 75
   at TrashLib.Radarr.CustomFormat.CustomFormatUpdater.Process(Boolean isPreview, RadarrConfiguration config) in D:\a\trash-updater\trash-updater\src\TrashLib\Radarr\CustomFormat\CustomFormatUpdater.cs:line 49
   at Trash.Command.RadarrCommand.Process() in D:\a\trash-updater\trash-updater\src\Trash\Command\RadarrCommand.cs:line 59

```

**Comment by rcdailey** [comment]
Do you mind providing your `trash.yml` as well as the corresponding logs in Radarr?

**Comment by darsh12** [comment]
## trash.yml
```yaml
# Configuration specific to Radarr.
radarr:
  # Set the URL/API Key to your actual instance
  - base_url: http://localhost:9999
    api_key: <API>

    # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'

    # Set to 'true' to automatically remove custom formats from Radarr when they are removed from
    # the guide or your configuration. This will NEVER delete custom formats you manually created!
    delete_old_custom_formats: false

    custom_formats:
      # A list of custom formats to sync to Radarr. Must match the "name" in the importable JSON.
      # Do NOT use the heading names here, those do not work! These are case-insensitive.
      - names:
          - BR-DISK
          - LQ
          - x265 (720/1080p)
          - 3D

        # Uncomment the below properties to specify one or more quality profiles that should be
        # updated with scores from the guide for each custom format. Without this, custom formats
        # are synced to Radarr but no scores are set in any quality profiles.

        quality_profiles:
          - name: Movie
            score: -9999 # Optional score to assign to all CFs. Overrides scores in the guide.
#            #reset_unmatched_scores: true # Optionally set other scores to 0 if they are not listed in 'names' above.
```

## running trash-updater

```bash
user in ~/trash-linux-x64 took 2s [I] ➜ ./trash radarr -d                                                                                                               media ✘1 
[DBG] Custom format cache does not exist; proceeding without it

[DBG] HTTP Request to http://hostname:9999/api/v3/customformat?apikey=SNIP
[DBG] HTTP Request to http://hostname:9999/radarr/api/v3/customformat?apikey=SNIP
[DBG] HTTP Response 200 from http://hostname:9999/radarr/api/v3/customformat?apikey=SNIP
[DBG] HTTP Response 302 from http://hostname:9999/api/v3/customformat?apikey=SNIP
[DBG] HTTP Request to http://hostname:9999/api/v3/customformat?apikey=SNIP
[DBG] HTTP Request to http://hostname:9999/radarr/api/v3/customformat?apikey=SNIP
[DBG] HTTP Response 200 from http://hostname:9999/radarr/api/v3/customformat?apikey=SNIP
[DBG] HTTP Response 302 from http://hostname:9999/api/v3/customformat?apikey=SNIP
[ERR] HTTP error while communicating with Radarr
Flurl.Http.FlurlParsingException: Response could not be deserialized to JSON: GET http://localhost:9999/radarr/api/v3/customformat?apikey=f7b15e28f1014ebe9671d4103d626dae
 ---> Newtonsoft.Json.JsonSerializationException: Deserialized JSON type 'Newtonsoft.Json.Linq.JArray' is not compatible with expected type 'Newtonsoft.Json.Linq.JObject'. Path '', line 1, position 2.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(JsonReader reader, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Flurl.Http.Configuration.NewtonsoftJsonSerializer.Deserialize[T](Stream stream)
   at Flurl.Http.FlurlResponse.GetJsonAsync[T]()
   --- End of inner exception stack trace ---
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlResponse.GetJsonAsync[T]()
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at TrashLib.Radarr.CustomFormat.Api.CustomFormatService.CreateCustomFormat(ProcessedCustomFormatData cf) in D:\a\trash-updater\trash-updater\src\TrashLib\Radarr\CustomFormat\Api\CustomFormatService.cs:line 28
   at TrashLib.Radarr.CustomFormat.Processors.PersistenceSteps.CustomFormatApiPersistenceStep.Process(ICustomFormatService api, CustomFormatTransactionData transactions) in D:\a\trash-updater\trash-updater\src\TrashLib\Radarr\CustomFormat\Processors\PersistenceSteps\CustomFormatApiPersistenceStep.cs:line 12
   at TrashLib.Radarr.CustomFormat.Processors.PersistenceProcessor.PersistCustomFormats(IReadOnlyCollection`1 guideCfs, IEnumerable`1 deletedCfsInCache, IDictionary`2 profileScores) in D:\a\trash-updater\trash-updater\src\TrashLib\Radarr\CustomFormat\Processors\PersistenceProcessor.cs:line 75
   at TrashLib.Radarr.CustomFormat.CustomFormatUpdater.Process(Boolean isPreview, RadarrConfiguration config) in D:\a\trash-updater\trash-updater\src\TrashLib\Radarr\CustomFormat\CustomFormatUpdater.cs:line 49
   at Trash.Command.RadarrCommand.Process() in D:\a\trash-updater\trash-updater\src\Trash\Command\RadarrCommand.cs:line 59
Exiting due to previous exception

```

## relevant radarr log
```text
2022-03-20 08:46:42.9|Debug|Api|[GET] /api/v3/customformat?apikey=(removed) 302.Redirect (1 ms)
2022-03-20 08:46:43.2|Debug|Api|[POST] /api/v3/customformat?apikey=(removed) 302.Redirect (0 ms)
```

**Comment by rcdailey** [comment]
Are you using a reverse proxy?

**Comment by darsh12** [comment]
Not in this particular instance. Both radarr and trash-updater and running on the same machine and I'm using localhost for the connection

**Comment by rcdailey** [comment]
Radarr is redirecting you which means your url is wrong. Can you fix that and retest? Might be that you are using radarr/ at the end and that's not valid.

**Comment by darsh12** [comment]
> Radarr is redirecting you which means your url is wrong. Can you fix that and retest? Might be that you are using radarr/ at the end and that's not valid.

Holy cow I totally forgot about that. When I added `/radarr` to the url it worked. 
Thank you very much! :)

**Comment by JP-Ellis** [comment]
Great to see this fixed so quickly!

In addition to putting it in the documentation, would it be worth adding some code logic to either:
- Follow redirects (at least a couple of times, e.g. `http://foo.bar/` to `https://foo.bar/` to `https://foo.bar/path/`)?
- Give a warning if any/too many redirects are detected and suggest that the path be added?

This would help a lot especially if someone doesn't read the troubleshooting help :sweat_smile:

**Comment by rcdailey** [comment]
Redirects were followed already but it still failed. I actually disabled redirects in this change and it now spits a warning out. Users really just need to be using the correct URL.
