### ISSUE TITLE
Issue w/ version check. Possible to bypass?

### ISSUE THREAD

**Issue by seannymurrs** [rcdailey/trash-updater#48]
I am running Sonarr and Radarr on my Whatbox slot. Whatbox uses a custom version of both apps as they handle the installation and updating of the apps themselves. Because of this, I’m getting a version error when attempting to run trash-updater. The exact error I'm receiving is below. Is there any way to bypass the version check since I'm pretty sure it should actually still work?

```
[INF] Processing Release Profile: Anime
[ERR] Unrecoverable Exception
TrashLib.ExceptionTypes.VersionException: Your Sonarr version 3.0.0.0 does not meet the minimum required version of 3.0.4.1098 to use this program
   at TrashLib.Sonarr.ReleaseProfile.ReleaseProfileUpdater.DoVersionEnforcement() in D:\a\trash-updater\trash-updater\src\TrashLib\Sonarr\ReleaseProfile\ReleaseProfileUpdater.cs:line 60
   at TrashLib.Sonarr.ReleaseProfile.ReleaseProfileUpdater.ProcessReleaseProfiles(IDictionary`2 profiles, ReleaseProfileConfig config) in D:\a\trash-updater\trash-updater\src\TrashLib\Sonarr\ReleaseProfile\ReleaseProfileUpdater.cs:line 131
   at TrashLib.Sonarr.ReleaseProfile.ReleaseProfileUpdater.Process(Boolean isPreview, SonarrConfiguration config) in D:\a\trash-updater\trash-updater\src\TrashLib\Sonarr\ReleaseProfile\ReleaseProfileUpdater.cs:line 51
   at Trash.Command.SonarrCommand.Process() in D:\a\trash-updater\trash-updater\src\Trash\Command\SonarrCommand.cs:line 51
   at Trash.Command.ServiceCommand.ExecuteAsync(IConsole console) in D:\a\trash-updater\trash-updater\src\Trash\Command\ServiceCommand.cs:line 53
```

**Comment by rcdailey** [comment]
There is no way to bypass it and I will not add one since the version check is required for proper behavior. The real issue here is they are not using a correct version number in their custom builds. That should be fixed.
