### ISSUE TITLE
Error after upgrading from Ubuntu 20.04 to Ubuntu 22.04

### ISSUE THREAD

**Issue by Banjer** [rcdailey/trash-updater#54]
Since updating my server from ubuntu 20.04 to 22.04 i'm getting an error when running the radarr sync. The sonarr sync seems to run fine.
If you need more information, please let me know.

[ERR] An exception occurred during git operations on path: /home/bas/.config/trash-updater/repo
LibGit2Sharp.LibGit2SharpException: could not load ssl libraries
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts) in /_/LibGit2Sharp/Core/Proxy.cs:line 275
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options) in /_/LibGit2Sharp/Repository.cs:line 793
   at VersionControl.Wrappers.LibGit2SharpRepositoryStaticWrapper.Clone(String sourceUrl, String workdirPath, CloneOptions options) in D:\a\trash-updater\trash-updater\src\VersionControl\Wrappers\LibGit2SharpRepositoryStaticWrapper.cs:line 8
   at VersionControl.GitRepositoryFactory.DeleteAndCloneRepo(String repoUrl, String repoPath, String branch) in D:\a\trash-updater\trash-updater\src\VersionControl\GitRepositoryFactory.cs:line 42
   at VersionControl.GitRepositoryFactory.CreateAndCloneIfNeeded(String repoUrl, String repoPath, String branch) in D:\a\trash-updater\trash-updater\src\VersionControl\GitRepositoryFactory.cs:line 27
   at TrashLib.Radarr.CustomFormat.Guide.LocalRepoCustomFormatJsonParser.CheckoutAndUpdateRepo() in D:\a\trash-updater\trash-updater\src\TrashLib\Radarr\CustomFormat\Guide\LocalRepoCustomFormatJsonParser.cs:line 68
[INF] Deleting local git repo and retrying git operation...
[1]    257872 segmentation fault (core dumped)  ./trash radarr

**Comment by rcdailey** [comment]
Are you running 32 or 64-bit Ubuntu? And which version and architecture of Trash Updater did you download and run? Also please post the debug logs (you can find instructions [here](https://github.com/rcdailey/trash-updater/wiki/Troubleshooting#obtaining-debug-logs)).

**Comment by Banjer** [comment]
I'm running Ubuntu 64-bit and i'm using trash-linux-x64 (version 1.8.2)

[trash_2022-04-25_22-16-21.log](https://github.com/rcdailey/trash-updater/files/8557680/trash_2022-04-25_22-16-21.log)

**Comment by Banjer** [comment]
Did some research and as far as i can see it might be related to the move from openssl 1.1 to openssl 3 Ubuntu made with 22.04

**Comment by Banjer** [comment]
"fixed" the problem by installing the libssl package from Ubuntu 21.10 (https://packages.ubuntu.com/impish-updates/libssl1.1)
After installing that package the updater ran as expected, removing the package broke trash-updater again.
So far no other effects observed, but i don't think this is the best solution. Hope LibGit2Sharp will get updated to support libssl3.0

**Comment by rcdailey** [comment]
Thanks a ton for researching this for me. I did about 5 minutes of Googling but I didn't come up with anything. I had a feeling it was something specific to SSL on Ubuntu 22, but I was going to set up a VirtualBox instance with it to verify. Looks like you saved me a lot of trouble, though!

I'm going to leave this issue open until some updates happen to the Troubleshooting wiki page. I'd like to document this issue for others that run into it.

**Comment by tpdcl** [comment]
This also happens to me on Fedora Server 36.
