### ISSUE TITLE
latest release broken

### ISSUE THREAD

**Issue by Motophan** [rcdailey/trash-updater#6]
`ERROR
Autofac.Core.Registration.ComponentNotRegisteredException: The requested service 'Trash.CreateConfig.CreateConfigCommand' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
  at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
  at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
  at Trash.Command.CliTypeActivator.ResolveType(IContainer container, Type typeToResolve)
  at Trash.Program.<>c.<Main>b__1_0(Type type)
  at CliFx.Infrastructure.DelegateTypeActivator.CreateInstance(Type type)
  at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput)
  at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables)
`

Fix: use release previously

**Comment by NBSDEVApp** [comment]
Same on Mac and Windows release

**Comment by rcdailey** [comment]
Thank you for the report and I apologize for overlooking this. This is resolved in [v1.3.2](https://github.com/rcdailey/trash-updater/releases/tag/v1.3.2).

**Comment by Motophan** [comment]
wait hold on you're doing us a favor don't apologize. this software is awesome.
